name: fetch html

on:
  workflow_dispatch:

jobs:
  fetch-html:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: fetch website html
      run: |
        curl -o output.html "https://example.com"
        cat output.html
